# fly.toml app configuration file generated for money-made-eth on 2025-02-03T23:39:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'money-made-eth'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
